site_name: æ–‡æ¡£å³äº§å“
site_author: Aaron Wang
site_url: https://materialx.shenwy.com/
site_description: mkdocsæ•™ç¨‹ï¼Œmarkdownæ•™ç¨‹ï¼Œmarkdownç”ŸæˆPPTã€é™æ€ç½‘ç«™ã€å›¾è¡¨ã€æ€ç»´å¯¼å›¾ï¼Œmarkdownç¼–å†™AIç»“æ„åŒ–æç¤ºè¯
copyright: Copyright &copy; 2025 | ğŸš€ Aaron Wang

repo_url: https://github.com/jaywhj
repo_name: aaron - repo

# æ§åˆ¶ç”Ÿæˆçš„æ–‡æ¡£ç›®å½•ç»“æ„ï¼Œfalse è¡¨ç¤ºä¸ç”Ÿæˆæ–‡ä»¶å¤¹ç›®å½•ï¼Œç›´æ¥æŒ‡å‘æ–‡ä»¶
use_directory_urls: false

# è®¾ç½®æ’é™¤æ–‡ä»¶å’Œæ–‡ä»¶å¤¹
exclude_docs: |
  /drafts/

# å¯¼èˆªç‰ˆå—
nav:
  - é¦–é¡µ: index.md
  - ä¸‹ä¸€ä»£ä¸»é¢˜æ’ä»¶ MaterialX: materialx-for-mkdocs.md
  - Markdown ç³»åˆ—:
    - Markdown å®ç”¨è¯­æ³•: markdown.md
    - æ—¥æœŸä½œè€…å¤´åƒæ’ä»¶: document-dates-zh.md
  - æ•ˆç‡æå‡:
    - æœ€è¿‘æ›´æ–°åˆ—è¡¨æ’ä»¶: recently-updated-zh.md
    - æµ·å—: hainan.md
  - æœ€è¿‘æ›´æ–°: RECENTLY_UPDATED.md
  # - åšå®¢: 
    # - blog/index.md

# ä¸»é¢˜æ¿å—
theme:
  name: materialx
  custom_dir: docs/overrides  # é…ç½®è¦†å†™æ–‡ä»¶ç›®å½•
  icon:
    logo: octicons/home-24
    repo: material/github
  language: zh
  font: false

  palette:
    - media: "(prefers-color-scheme: light)"   # æ‰‹åŠ¨æ¨¡å¼ - äº®è‰²
      scheme: default
      primary: indigo
      accent: light indigo
      toggle:
        icon: material/weather-sunny
        name: äº®è‰²æ¨¡å¼
    - media: "(prefers-color-scheme: dark)"    # æ‰‹åŠ¨æ¨¡å¼ - æš—è‰²
      scheme: slate
      primary: cyan
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: æš—è‰²æ¨¡å¼

  features:
    # - header.autohide   # è‡ªåŠ¨éšè—header

    - navigation.tabs         # å¯¼èˆªæ æ˜¾ç¤ºåœ¨é¡¶éƒ¨tabé‡Œ
    - navigation.top          # è¿”å›é¡¶éƒ¨æŒ‰é’®
    # - navigation.indexes      # å¯ç”¨ç« èŠ‚ç´¢å¼•é¡µï¼Œæ–‡æ¡£å¯ç›´æ¥é™„åŠ åˆ°ç« èŠ‚
    # - navigation.tabs.sticky  # é¡¶éƒ¨å¯¼èˆªæ å§‹ç»ˆå¯è§
    # - navigation.expand       # é»˜è®¤å±•å¼€ä¾§è¾¹å¯¼èˆªæ 
    # - navigation.sections     # ä¾§è¾¹å¯¼èˆªæ åˆ†ç»„æ˜¾ç¤ºï¼Œä¸ç¼©è¿›æ— æŠ˜å 
    # - navigation.prune        # åªæ¸²æŸ“å¯è§çš„å¯¼èˆªé¡¹ï¼Œä»è€Œå‡å°‘æ„å»ºç«™ç‚¹çš„å¤§å°ï¼ˆéœ€å…³é—­ navigation.expandï¼Œå¼€å¯åä¼šå½±å“ç”¨æˆ·ä½“éªŒï¼Œæ¯”å¦‚æŠ˜å çš„åˆ†ç»„å±•å¼€æ—¶å°±æ²¡æ³•æ˜¾ç¤ºæ–‡ç« åˆ—è¡¨äº†ï¼‰
    # - navigation.instant      # å¯ç”¨å³æ—¶åŠ è½½ï¼Œæ— éœ€å®Œå…¨é‡æ–°åŠ è½½é¡µé¢ï¼Œå¯¹äºå¤§å‹æ–‡æ¡£ç«™ç‚¹æœ‰ç”¨ï¼ˆæ‰€æœ‰å†…éƒ¨é“¾æ¥çš„äº‹ä»¶éƒ½å°†è¢«æ‹¦æˆªå¹¶é€šè¿‡ XHR å‘é€ï¼‰
    # - navigation.instant.prefetch # å¯ç”¨å³æ—¶é¢„å–ï¼Œç”¨æˆ·å°†é¼ æ ‡æ‚¬åœåœ¨é“¾æ¥ä¸Šï¼Œå°±ä¼šå¼€å§‹æå–é¡µé¢ï¼Œè¿™å‡å°‘äº†ç”¨æˆ·çš„æ„ŸçŸ¥åŠ è½½æ—¶é—´
    # - navigation.tracking     # é”šç‚¹è·Ÿè¸ªï¼Œåœ°å€æ ä¸­çš„ URL ä¼šè‡ªåŠ¨æ›´æ–°ä¸ºæ´»åŠ¨é”šç‚¹
    - navigation.footer       # åº•éƒ¨å¯¼èˆªæ 

    - content.code.copy # å¤åˆ¶ä»£ç æŒ‰é’®
    - content.tooltips  # å¯ç”¨æ¼‚äº®çš„æç¤ºå·¥å…·ï¼Œå–ä»£æµè§ˆå™¨é»˜è®¤æ ·å¼
    - content.footnote.tooltips # æ‚¬åœæ˜¾ç¤ºè„šæ³¨ï¼Œå¯ä»¥åœ¨ä¸ç¦»å¼€æ–‡æ¡£ä¸Šä¸‹æ–‡çš„æƒ…å†µä¸‹é˜…è¯»è„šæ³¨
    - search.highlight  # æœç´¢ç»“æœé«˜äº®
    - toc.follow        # æ»šåŠ¨çš„æ—¶å€™ä¾§è¾¹æ è‡ªåŠ¨è·Ÿéš
    # - toc.integrate     # ç›®å½•å¯¼èˆªé›†æˆï¼ŒTOCæ€»æ˜¯ä½œä¸ºå·¦ä¾§å¯¼èˆªä¾§è¾¹æ çš„ä¸€éƒ¨åˆ†å‘ˆç°

# markdown å±æ€§æ‰©å±•
markdown_extensions:
  # ç»™ mkdocs çš„è§£æå™¨ python-markdown æ·»åŠ æ¢è¡Œæ‰©å±•
  # https://python-markdown.github.io/extensions/nl2br/
  - nl2br

  - abbr                # ç¼©ç•¥è¯­æç¤ºå°å·¥å…·
  - admonition          # æ‰©å±•å¼¹å‡ºè­¦å‘Šæ¡†ï¼Œé€šå¸¸ç§°ä¸º call-outs
  - attr_list           # æ‰©å±•ç»™å…ƒç´ æ·»åŠ HTML/CSSå±æ€§çš„åŠŸèƒ½
  - def_list            # æ‰©å±•å°†å®šä¹‰åˆ—è¡¨æ·»åŠ åˆ°æ–‡æ¡£
  - footnotes           # è„šæ³¨
  - md_in_html          # è§£æ html ä¸­çš„ markdown
  - tables              # å¢å¼ºè¡¨æ ¼

  - pymdownx.betterem   # æ–‡æœ¬æ ·å¼åŠ å¼º
  - pymdownx.caret      # ä¸Šæ ‡ã€æ’å…¥ç¬¦å·
  - pymdownx.mark       # æ ‡è®°ã€==é«˜äº®==
  - pymdownx.tilde      # ä¸‹æ ‡ã€æ³¢æµªç¬¦
  - pymdownx.critic     # æ‰¹æ³¨æ ‡è®°ï¼Œçªå‡ºæ˜¾ç¤ºæ–‡æ¡£ä¸­æ·»åŠ ã€åˆ é™¤æˆ–æ›´æ–°çš„éƒ¨åˆ†
  - pymdownx.details    # å¯æŠ˜å çš„å— Noteï¼Œæ”¯æŒï¼šæ ‡æ³¨ã€æ‰¹æ³¨ã€è­¦å‘Šã€å¼•ç”¨ç­‰
  - pymdownx.smartsymbols   # æ™ºèƒ½ç¬¦å·ï¼Œå¦‚ (tm) â†’ â„¢
  - pymdownx.snippets   # å°†ä»»æ„æ–‡ä»¶å†…å®¹åµŒå…¥åˆ°æ–‡æ¡£
  - pymdownx.blocks.caption # å‘ Markdown å—æ·»åŠ æ ‡é¢˜ï¼ŒåŒ…æ‹¬å›¾åƒã€è¡¨æ ¼å’Œä»£ç å—
  - pymdownx.inlinehilite   # å†…è”ä»£ç é«˜äº®ï¼Œå»ºç«‹åœ¨ highlight åŸºç¡€ä¸Š
  - pymdownx.keys           # æ‰©å±•é”®ç›˜æ¸²æŸ“-æŒ‰é”®ç»„åˆå†™æ³•

  - pymdownx.tasklist:      # ä»»åŠ¡åˆ—è¡¨
      custom_checkbox: true     # åˆ‡æ¢å¤é€‰æ¡†æ¸²æŸ“æ ·å¼ï¼Œç”¨æ¼‚äº®çš„å›¾æ ‡æ›¿æ¢åŸç”Ÿçš„
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:     # æ‰©å±•ä»£ç é«˜äº®
      use_pygments: true    # ä½¿ç”¨ pygments æ¥æ‰§è¡Œä»£ç é«˜äº®
      pygments_lang_class: true
      # auto_title: true      # æ˜¾ç¤ºç¼–ç¨‹è¯­è¨€åç§°
      linenums: true        # æ˜¾ç¤ºè¡Œå·
      linenums_style: pymdownx-inline # è¡Œå·æ ·å¼ï¼Œé˜²æ­¢å¤åˆ¶çš„æ—¶å€™å¤åˆ¶è¡Œå·
      anchor_linenums: true
      line_spans: __span    # ä»£ç å—çš„æ¯ä¸€è¡Œéƒ½åŒ…å«åœ¨ span ä¸­ï¼Œå¯¹äºè¡Œçªå‡ºæ˜¾ç¤ºåŠŸèƒ½æœ‰å¿…è¦
  - pymdownx.tabbed:        # å†…å®¹é€‰é¡¹å¡
      alternate_style: true # å¯ç”¨å†…å®¹é€‰é¡¹å¡æ›¿ä»£æ ·å¼
      combine_header_slug: true  # å°†æ ‡é¢˜çš„ id æ·»åŠ åˆ°é€‰é¡¹å¡çš„ id ä¹‹å‰
  - pymdownx.arithmatex:    # æ•°å­¦å…¬å¼å¼€å…³ï¼Œè¿˜éœ€é…ç½®è§£ææ’ä»¶æºï¼ˆmathjax/katex äºŒé€‰ä¸€ï¼‰
      generic: true
  - pymdownx.superfences:   # è¶…çº§æ …æ ï¼Œå…è®¸ä»£ç å’Œå†…å®¹å—ä»»æ„åµŒå¥—ï¼ˆå„ç§å›¾ã€æ³¨è§£ã€é€‰é¡¹å¡ã€ä»£ç å—ç­‰ï¼‰
      custom_fences:
        - name: mermaid     # é…ç½® mermaid ç»˜å›¾
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      toc_depth: 4      # ç›®å½•æ·±åº¦
      permalink: true   # åœ¨æ¯ä¸ªæ ‡é¢˜çš„æœ«å°¾æ·»åŠ æ®µè½ç¬¦ Â¶
      slugify: !!python/object/apply:pymdownx.slugs.slugify {}  # é”šç‚¹é“¾æ¥ï¼šç»Ÿä¸€å­—ç¬¦ç¼–ç ï¼ŒåŒºåˆ†å¤§å°å†™
      # slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}

# é¢å¤–é…ç½®æ¿å—
extra:
  generator: false  # éšè—é¡µè„š â€œMade with Material for MkDocsâ€
  social:   # å³ä¸‹è§’çš„ç¤¾äº¤æŒ‰é’®
    - icon: fontawesome/brands/github
      link: https://github.com/jaywhj
      name: GitHub
    - icon: material/email
      link: mailto:junewhj@qq.com
      name: Email

  # å¤šè¯­è¨€é€‰æ‹©ï¼ˆå¯éšæ„å¢åˆ ï¼‰
  alternate:
    - name: ğŸ‡¨ğŸ‡³ ä¸­æ–‡
      lang: zh
    - name: ğŸ‡ºğŸ‡¸ English
      lang: en
    - name: ğŸ‡©ğŸ‡ª Deutsch
      lang: de
    - name: ğŸ‡·ğŸ‡º Ğ ÑƒÑÑĞºĞ¸Ğ¹
      lang: ru
    - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èª
      lang: ja
    - name: ğŸ‡³ğŸ‡± Dutch
      lang: nl
    - name: ğŸ‡«ğŸ‡· FranÃ§ais
      lang: fr
    - name: ğŸ‡ªğŸ‡¸ EspaÃ±ol
      lang: es
    - name: ğŸ‡§ğŸ‡· PortuguÃªs
      lang: pt
    - name: ğŸ‡¸ğŸ‡¦ Ø§Ù„Ø¹Ø±Ø¨ÙŠØ©
      lang: ar
    - name: ğŸ‡°ğŸ‡· í•œêµ­ì–´
      lang: ko

# æ’ä»¶æ¿å—
plugins:
  # - blog        # å†…ç½®åšå®¢æ’ä»¶
  # - tags        # å†…ç½®æ ‡ç­¾æ’ä»¶ï¼Œå¯¹é¡µé¢è¿›è¡Œåˆ†ç±»
  - search      # å†…ç½®æœç´¢æ’ä»¶
  - offline     # å†…ç½®ç¦»çº¿æ’ä»¶ï¼Œå¯ç¦»çº¿è®¿é—®ç½‘ç«™ï¼Œæ’ä»¶ä¼šè‡ªåŠ¨ç¦ç”¨ use_directory_urls è®¾ç½®

  # æ–‡æ¡£æ—¥æœŸã€ä½œè€…ã€å¤´åƒæ’ä»¶
  - document-dates:     # https://github.com/jaywhj/mkdocs-document-dates
      type: timeago
      exclude:
        - index.md
        - blog/*
        - RECENTLY_UPDATED.md
      recently-updated:
        limit: 10
        exclude:
          - index.md
          - blog/*

  # å›¾ç‰‡ç¯ç®±ç‰¹æ•ˆæ’ä»¶
  - glightbox

extra_javascript:
  # é…ç½® full ç‰ˆæœ¬çš„ timeago
  - assets/document_dates/core/timeago.full.min.js

  # åŠ è½½ç¿»è¯‘æ’ä»¶ translate
  - javascripts/translate.min.js
  - javascripts/extra.js

  # é…ç½®æ•°å­¦å…¬å¼è§£æåº“ katex è·¯å¾„
  - site-plugin/katex/katex.js
  - site-plugin/katex/katex.min.js
  - site-plugin/katex/auto-render.min.js
  # æ”¯æŒåŒ–å­¦æ–¹ç¨‹å¼
  - site-plugin/katex/mhchem.min.js

extra_css:
  # é…ç½® katex æ ·å¼
  - site-plugin/katex/katex.min.css
